# Generated by Django 4.2.2 on 2023-06-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField()),
                ("title", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=50, unique=True)),
                ("tracks", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=250)),
                ("is_verified_by_admin", models.BooleanField()),
                ("conference_website", models.CharField(max_length=250)),
            ],
            options={
                "db_table": "conference",
            },
        ),
    ]
